export default{
    item1: require("../images/item-cart-01.jpg"),
    item2: require("../images/item-cart-02.jpg"),
    item5: require("../images/blog-02.jpg"),
    item6: require("../images/item-03.jpg"),
    carousel1: require("../images/carousel1.jpg"),
    carousel2: require("../images/carousel2.jpg"),
    banner1: require("../images/banner-02.jpg"),
    banner2: require("../images/banner-07.jpg"),
    item3: require("../images/item-02.jpg"),
    item4: require("../images/item-05.jpg"),
    glasses: require("../images/shop-item-09.jpg"),
    watch: require("../images/item-cart-03.jpg"),
    blog1: require("../images/blog-01.jpg"),
    blog2: require("../images/blog-02.jpg"),
    blog3: require("../images/blog-03.jpg"),
}